Сбербанк_страхование - Страхование путешественников - https://auth.sberbankins.ru/auth/realms/insure-app/protocol/openid-connect/auth?client_id=lk-app&redirect_uri=https%3A%2F%2Fonline.sberbankins.ru%2Fnewlk%2F&state=c82d0192-48bd-48cc-a5bd-adaca1f4a030&response_mode=fragment&response_type=code&scope=openid&nonce=c5a0c6b6-6cc9-42fc-a1da-5af9df23ee9c - 2023-06-25 14:25:58 - HTTPSConnectionPool(host='auth.sberbankins.ru', port=443): Max retries exceeded with url: /auth/realms/insure-app/protocol/openid-connect/auth?client_id=lk-app&redirect_uri=https%3A%2F%2Fonline.sberbankins.ru%2Fnewlk%2F&state=c82d0192-48bd-48cc-a5bd-adaca1f4a030&response_mode=fragment&response_type=code&scope=openid&nonce=c5a0c6b6-6cc9-42fc-a1da-5af9df23ee9c (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbdce144d90>, 'Connection to auth.sberbankins.ru timed out. (connect timeout=2)'))
Сбербанк_страхование - Страхование путешественников - https://auth.sberbankins.ru/auth/realms/insure-app/protocol/openid-connect/auth?client_id=lk-app&redirect_uri=https%3A%2F%2Fonline.sberbankins.ru%2Fnewlk%2F&state=c82d0192-48bd-48cc-a5bd-adaca1f4a030&response_mode=fragment&response_type=code&scope=openid&nonce=c5a0c6b6-6cc9-42fc-a1da-5af9df23ee9c - 2023-06-25 14:26:06 - Восстановление
